defaults : &defaults
  host: postgres
  adapter: postgres
  user: postgres
  password: postgres
  migration_files_path: db/migrations

development:
  db: kemal
  <<: *defaults

test:
  db: kemal_test
  <<: *defaults